version: "3.9"

# 共通設定部分
x-common-settings: &common-settings
  tty: true
  volumes:
    - ./apt-fast.conf:/etc/apt-fast.conf:ro
  networks:
    - gui-net
    - db-net

services:
  # AtCoderサービス
  atcoder:
    container_name: atcoder
    image: atcoder
    build:
      context: ./atcoder
      dockerfile: Dockerfile
    volumes:
      - ./../AtCoder:/root/atcoder
    <<: *common-settings

  # Cassandraデータベースサービス
  cassandra:
    image: cassandra:4
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./../DataBase/cassandra:/var/lib/cassandra
    <<: *common-settings

  # C/C++ 開発環境
  c_cpp:
    container_name: c_cpp
    image: c_cpp
    build:
      context: ./c_cpp
      dockerfile: Dockerfile
    volumes:
      - ./../C&C++:/root/c_cpp
    <<: *common-settings

  # CUDA 開発環境
  cuda:
    container_name: cu
    image: cu
    build:
      context: ./cu
      dockerfile: Dockerfile
    volumes:
      - ./../Cuda:/root/cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    <<: *common-settings

  # Elasticsearchサービス
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./../DataBase/es:/usr/share/elasticsearch/data
    <<: *common-settings

  # GUIサービス（noVNC）
  gui:
    container_name: gui
    image: gui
    build:
      context: ./gui
      dockerfile: Dockerfile
    volumes:
      - ./../GUI:/root/Desktop
    <<: *common-settings
    ports:
      - "6080:6080"

  # Java開発環境
  java:
    container_name: java
    image: java
    build:
      context: ./java
      dockerfile: Dockerfile
    volumes:
      - ./../Java:/root/java
    <<: *common-settings

  # JavaScript開発環境
  javascript:
    container_name: js
    image: js
    build:
      context: ./js
      dockerfile: Dockerfile
    volumes:
      - ./../JavaScript:/root/js
    <<: *common-settings

  # MariaDBデータベース
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: testdb
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    volumes:
      - ./../DataBase/maria:/var/lib/mysql
    <<: *common-settings

  # MongoDBデータベース
  mongodb:
    image: mongo:7
    container_name: mongodb
    volumes:
      - ./../DataBase/mongo:/data/db
    <<: *common-settings

  # MSSQLデータベース
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-lts
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong!Pass123"
    volumes:
      - ./../DataBase/mssql:/var/opt/mssql
    <<: *common-settings

  # MySQLデータベース
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./../DataBase/mysql:/var/lib/mysql
    <<: *common-settings

  # Oracleデータベース
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0
    container_name: oracle-xe
    environment:
      ORACLE_PWD: "OraclePwd123"
      ORACLE_ALLOW_REMOTE: "true"
    volumes:
      - ./../DataBase/oracle:/opt/oracle/oradata
    <<: *common-settings

  # PostgreSQLデータベース
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    volumes:
      - ./../DataBase/postgres:/var/lib/postgresql/data
    <<: *common-settings

  # Python開発環境
  python:
    container_name: py
    image: py
    build:
      context: ./py
      dockerfile: Dockerfile
    volumes:
      - ./../Python:/root/py
    <<: *common-settings

  # Redisデータベース
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - ./../DataBase/redis:/data
    <<: *common-settings

  # SQLite-webサービス
  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    volumes:
      - ./../DataBase/sqlite:/data
    command: sqlite-web /data/test.db
    <<: *common-settings

networks:
  gui-net:
    name: gui-net
  db-net:
    name: db-net
